### ISSUE TITLE
New update breaks Webpack build

### ISSUE THREAD

**Issue by TimonLukas** [mapbox/polylabel#60]
Hello! While updating the dependencies of one of our apps we just noticed that `polylabel` got an update. Sadly this update breaks the module for our frontends, because with `tinyqueue`s export syntax the imported module is no longer the class constructor, which instead lies in `require('tinyqueue').default`. This is the error message we are getting:

```
Uncaught TypeError: Queue is not a constructor
```

We've fixed it for now by pinning `tinyqueue` to version `1.2.2`, but this isn't a great solution. Any tips on how we could fix this? Or is there potentially any way for you to fix this on your side? (e. g. by checking if a `default` property exists on the import)

Thank you!

**Comment by mourner** [comment]
Oh dear, I hate Webpack so much. Pushed a temporary fix in v1.0.5. Will migrate the project to ES / modules in v2.

**Comment by TimonLukas** [comment]
Thank you or the very quick fix, and for the heads-up! :)

**Comment by jonhermansen** [comment]
I ran into an issue with the most recent release, 1.0.5. It happened due to my app's dependency chain:

```
$ npm ls tinyqueue
my-project@1.2.3 /Users/jhermansen/Desktop/my-project
└─┬ @amcharts/amcharts4@4.5.12
  └─┬ polylabel@1.0.5
    └── tinyqueue@2.0.3
```

I think it was caused by 6854a05e221fac42b9e025cbf356b2a057f212aa while upgrading to tinyqueue 2.x, which has this bug https://github.com/mourner/tinyqueue/issues/12

My application needs to support IE 11 and so inadvertently we started bundling some JS code that was trying to use ES6 classes, which causes IE to stop loading our app entirely :(

I hope I don't come across as complainy. Thank you for building cool open source stuff, that I didn't even know we were using under the hood until today. 😃  I just thought this information may be helpful in case anyone else runs into it.

In my case, I was able to fix the issue by committing our package-lock.json file that had tinyqueue pinned to v1.2.3.
